name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
    - main  # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Debug - Check public directory
      run: |
        echo "=== Checking public directory ==="
        if [ -d "public" ]; then
          echo "Public directory exists"
          find public -type f -name "*.glb" -o -name "*.ico" -o -name "*.svg" | head -10
        else
          echo "Public directory does not exist"
        fi

    - name: Build Next.js app
      run: npm run build

    - name: Debug - Check out directory after build
      run: |
        echo "=== Checking out directory after build ==="
        if [ -d "out" ]; then
          echo "Out directory exists"
          ls -la out/
          echo "Looking for model files:"
          find out -name "*.glb" || echo "No .glb files found in out/"
        else
          echo "Out directory does not exist"
        fi

    - name: Manually copy public assets to out
      run: |
        echo "=== Manually copying public assets ==="
        if [ -d "public" ]; then
          # Create out directory if it doesn't exist
          mkdir -p out
          
          # Copy all files from public to out, preserving directory structure
          echo "Copying public/* to out/"
          cp -rv public/* out/ 2>/dev/null || echo "No files to copy or copy failed"
          
          # Specifically ensure model directory exists and copy model files
          if [ -d "public/model" ]; then
            echo "Copying model directory"
            mkdir -p out/model
            cp -v public/model/* out/model/ 2>/dev/null || echo "No model files to copy"
          fi
          
          # List what we have in out now
          echo "Contents of out/ after copying:"
          find out -type f | head -20
          
          # Verify model file specifically
          if [ -f "out/model/textured_mesh.glb" ]; then
            echo "✅ Model file successfully copied: $(ls -lh out/model/textured_mesh.glb)"
          else
            echo "❌ Model file not found after copying"
          fi
        else
          echo "Public directory not found, skipping copy"
        fi

    - name: Create .nojekyll file
      run: touch out/.nojekyll

    - name: Final verification
      run: |
        echo "=== Final verification ==="
        echo "Total files in out directory: $(find out -type f | wc -l)"
        echo "Directory structure:"
        tree out/ -L 3 2>/dev/null || find out -type d | head -10
        echo "Asset files:"
        find out -name "*.glb" -o -name "*.ico" -o -name "*.svg" | head -10

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.ANIMATION_WEB }}
        publish_dir: ./out
        keep_files: false
        force_orphan: false